### ISSUE TITLE
Potential lag issue over network

### ISSUE THREAD

**Issue by mwcraig** [astropy/astrowidgets#49] opened 2018-10-31 03:13 UTC
I was working with some students today via an example notebook using astrowidgets running on binder. Some of them noticed very substantial lag when panning. I'm not sure whether that is because of limitations of binder, or network speed or what. If you have a couple minutes and can give it a spin and report back that would be great.

To get to the example go to [this binder link](http://beta.mybinder.org/v2/gh/mwcraig/obs-astronomy-binder/master?filepath=2018-10-30.ipynb), run the first cell to download a couple of images, then click into the first notebook. 

It has a couple of vastly simplified mouse/keyboard bindings I wanted to run by the students today. It also supports right-click-and-drag to change contrast/cuts if you want to try that (shift-right-click to reset the contrast).

**Comment by mwcraig** [comment] 2018-10-31 03:14
Just tried this myself and I saw lag in one tab but none in another 🙄

**Comment by pllim** [comment] 2018-10-31 14:19
I am not sure if it is lag on my side. I noticed that using the scroll wheel, panning is slow because it moves the image very little per scroll distance (not sure what is the proper term for that).

Also the notebook says that you don't have `opencv` installed.Not sure if that matters here. @ejeschke?

**Comment by pllim** [comment] 2018-10-31 14:20
p.s. How do I get out of the binder gracefully? Is closing the tab enough?

**Comment by mwcraig** [comment] 2018-10-31 14:25
Ah, I didn't catch that opencv was missing. I'll look into that, thanks.

Closing the tab is enough. After ~10 minutes of inactivity the underlying process is killed.

**Comment by ejeschke** [comment] 2018-10-31 18:34
Scroll wheel under the pg widget is bound to the scroll event. If you are using a trackpad it would seem more normal.  The problem is that it can be difficult to detect the difference between the wheel and scrolling fingers on a trackpad, especially in the javascript environment.

Short of customizing the bindings for your particular case, you can use the modes to work around this a bit.  Press Space, 'w' to go into `freepan` mode, where scrolling zooms--there your mouse wheel (or trackpad) will zoom the image rather than scrolling. Space,  'q' puts you in `pan` mode where you can drag the image (or click in it) to pan.

`opencv` will help with the speed a little, especially rotations.

**Comment by ejeschke** [comment] 2018-10-31 18:37
In `pan` or `freepan` mode you can also use the arrow keys to adjust the pan in increments.

**Closed** 2023-06-16 15:07 UTC
Labels: bug, question
